"""
Seed data — 30+ realistic demo assessments for RiskPilot AI.
All monetary values in Indian Rupees (INR), stored as plain floats.
"""
import json
import random
from datetime import datetime, timedelta

from sqlalchemy.orm import Session

from models import Customer, RiskAssessment, RiskFactor, AuditLog
from engine.risk_engine import RiskEngine
from engine.explanation_engine import ExplanationEngine
from engine.recommendation_engine import RecommendationEngine
from engine.anomaly_engine import AnomalyEngine

_risk_engine = RiskEngine()
_explanation_engine = ExplanationEngine()
_recommendation_engine = RecommendationEngine()
_anomaly_engine = AnomalyEngine()


SEED_CASES = [
    # ============ DEMO CASE — CRITICAL ============
    {
        "customer_name": "Arun Kumar",
        "customer_id": "CUST-AK-001",
        "transaction_amount": 85000,
        "transaction_type": "Transfer",
        "location": "Mumbai",
        "previous_average_amount": 5000,
        "device_type": "Mobile",
        "is_new_device": True,
        "login_time": "02:47",
        "previous_location": "Chennai",
        "current_location": "Mumbai",
        "transaction_frequency": 15,
        "account_age_days": 180,
        "previous_risk_score": 72,
        "status": "Open",
    },
    # ============ CRITICAL Cases ============
    {
        "customer_name": "Priya Sharma",
        "customer_id": "CUST-PS-002",
        "transaction_amount": 120000,
        "transaction_type": "Withdrawal",
        "location": "Delhi",
        "previous_average_amount": 8000,
        "device_type": "Desktop",
        "is_new_device": True,
        "login_time": "03:15",
        "previous_location": "Pune",
        "current_location": "Delhi",
        "transaction_frequency": 12,
        "account_age_days": 45,
        "previous_risk_score": 65,
        "status": "Escalated",
    },
    {
        "customer_name": "Vikram Nair",
        "customer_id": "CUST-VN-003",
        "transaction_amount": 200000,
        "transaction_type": "Transfer",
        "location": "Hyderabad",
        "previous_average_amount": 10000,
        "device_type": "Mobile",
        "is_new_device": True,
        "login_time": "01:30",
        "previous_location": "Bangalore",
        "current_location": "Hyderabad",
        "transaction_frequency": 20,
        "account_age_days": 3,
        "previous_risk_score": 80,
        "status": "Under Review",
    },
    {
        "customer_name": "Sneha Reddy",
        "customer_id": "CUST-SR-004",
        "transaction_amount": 75000,
        "transaction_type": "Purchase",
        "location": "Chennai",
        "previous_average_amount": 3000,
        "device_type": "Tablet",
        "is_new_device": True,
        "login_time": "04:00",
        "previous_location": "Kolkata",
        "current_location": "Chennai",
        "transaction_frequency": 18,
        "account_age_days": 20,
        "previous_risk_score": 75,
        "status": "Open",
    },
    {
        "customer_name": "Rahul Mehta",
        "customer_id": "CUST-RM-005",
        "transaction_amount": 150000,
        "transaction_type": "Transfer",
        "location": "Ahmedabad",
        "previous_average_amount": 12000,
        "device_type": "Mobile",
        "is_new_device": True,
        "login_time": "02:00",
        "previous_location": "Surat",
        "current_location": "Ahmedabad",
        "transaction_frequency": 14,
        "account_age_days": 90,
        "previous_risk_score": 68,
        "status": "Escalated",
    },
    {
        "customer_name": "Deepa Krishnan",
        "customer_id": "CUST-DK-006",
        "transaction_amount": 95000,
        "transaction_type": "Withdrawal",
        "location": "Bangalore",
        "previous_average_amount": 6000,
        "device_type": "Desktop",
        "is_new_device": True,
        "login_time": "03:45",
        "previous_location": "Mumbai",
        "current_location": "Bangalore",
        "transaction_frequency": 11,
        "account_age_days": 5,
        "previous_risk_score": 55,
        "status": "Under Review",
    },
    # ============ HIGH Cases ============
    {
        "customer_name": "Kiran Patel",
        "customer_id": "CUST-KP-007",
        "transaction_amount": 45000,
        "transaction_type": "Transfer",
        "location": "Jaipur",
        "previous_average_amount": 8000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "01:50",
        "previous_location": "Delhi",
        "current_location": "Jaipur",
        "transaction_frequency": 8,
        "account_age_days": 200,
        "previous_risk_score": 60,
        "status": "Under Review",
    },
    {
        "customer_name": "Anjali Singh",
        "customer_id": "CUST-AS-008",
        "transaction_amount": 60000,
        "transaction_type": "Withdrawal",
        "location": "Lucknow",
        "previous_average_amount": 5000,
        "device_type": "Desktop",
        "is_new_device": True,
        "login_time": "14:30",
        "previous_location": "Lucknow",
        "current_location": "Lucknow",
        "transaction_frequency": 9,
        "account_age_days": 365,
        "previous_risk_score": 45,
        "status": "Open",
    },
    {
        "customer_name": "Suresh Babu",
        "customer_id": "CUST-SB-009",
        "transaction_amount": 35000,
        "transaction_type": "Purchase",
        "location": "Coimbatore",
        "previous_average_amount": 7000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "04:20",
        "previous_location": "Madurai",
        "current_location": "Coimbatore",
        "transaction_frequency": 6,
        "account_age_days": 730,
        "previous_risk_score": 52,
        "status": "Open",
    },
    {
        "customer_name": "Meera Iyer",
        "customer_id": "CUST-MI-010",
        "transaction_amount": 55000,
        "transaction_type": "Transfer",
        "location": "Kochi",
        "previous_average_amount": 9000,
        "device_type": "Mobile",
        "is_new_device": True,
        "login_time": "15:00",
        "previous_location": "Trivandrum",
        "current_location": "Kochi",
        "transaction_frequency": 5,
        "account_age_days": 400,
        "previous_risk_score": 38,
        "status": "Approved",
    },
    {
        "customer_name": "Arjun Kapoor",
        "customer_id": "CUST-AK2-011",
        "transaction_amount": 42000,
        "transaction_type": "Withdrawal",
        "location": "Chandigarh",
        "previous_average_amount": 10000,
        "device_type": "Desktop",
        "is_new_device": False,
        "login_time": "03:00",
        "previous_location": "Amritsar",
        "current_location": "Chandigarh",
        "transaction_frequency": 7,
        "account_age_days": 550,
        "previous_risk_score": 30,
        "status": "Open",
    },
    {
        "customer_name": "Pooja Gupta",
        "customer_id": "CUST-PG-012",
        "transaction_amount": 38000,
        "transaction_type": "Purchase",
        "location": "Bhopal",
        "previous_average_amount": 4000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "22:30",
        "previous_location": "Indore",
        "current_location": "Bhopal",
        "transaction_frequency": 11,
        "account_age_days": 120,
        "previous_risk_score": 25,
        "status": "Under Review",
    },
    {
        "customer_name": "Ravi Shankar",
        "customer_id": "CUST-RS-013",
        "transaction_amount": 28000,
        "transaction_type": "Transfer",
        "location": "Nagpur",
        "previous_average_amount": 6000,
        "device_type": "Desktop",
        "is_new_device": True,
        "login_time": "11:00",
        "previous_location": "Nagpur",
        "current_location": "Nagpur",
        "transaction_frequency": 4,
        "account_age_days": 800,
        "previous_risk_score": 20,
        "status": "Resolved",
    },
    {
        "customer_name": "Lakshmi Menon",
        "customer_id": "CUST-LM-014",
        "transaction_amount": 48000,
        "transaction_type": "Withdrawal",
        "location": "Vizag",
        "previous_average_amount": 7500,
        "device_type": "Tablet",
        "is_new_device": True,
        "login_time": "16:45",
        "previous_location": "Hyderabad",
        "current_location": "Vizag",
        "transaction_frequency": 6,
        "account_age_days": 300,
        "previous_risk_score": 40,
        "status": "Open",
    },
    # ============ MEDIUM Cases ============
    {
        "customer_name": "Amit Joshi",
        "customer_id": "CUST-AJ-015",
        "transaction_amount": 18000,
        "transaction_type": "Payment",
        "location": "Pune",
        "previous_average_amount": 7000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "10:30",
        "previous_location": "Pune",
        "current_location": "Pune",
        "transaction_frequency": 3,
        "account_age_days": 600,
        "previous_risk_score": 55,
        "status": "Open",
    },
    {
        "customer_name": "Nisha Tiwari",
        "customer_id": "CUST-NT-016",
        "transaction_amount": 15000,
        "transaction_type": "Purchase",
        "location": "Patna",
        "previous_average_amount": 5000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "09:00",
        "previous_location": "Ranchi",
        "current_location": "Patna",
        "transaction_frequency": 2,
        "account_age_days": 450,
        "previous_risk_score": 35,
        "status": "Approved",
    },
    {
        "customer_name": "Sandeep Rao",
        "customer_id": "CUST-SA-017",
        "transaction_amount": 22000,
        "transaction_type": "Transfer",
        "location": "Mysore",
        "previous_average_amount": 8000,
        "device_type": "Desktop",
        "is_new_device": False,
        "login_time": "13:15",
        "previous_location": "Bangalore",
        "current_location": "Mysore",
        "transaction_frequency": 4,
        "account_age_days": 900,
        "previous_risk_score": 28,
        "status": "Resolved",
    },
    {
        "customer_name": "Kavita Pillai",
        "customer_id": "CUST-KP2-018",
        "transaction_amount": 12000,
        "transaction_type": "Refund",
        "location": "Thrissur",
        "previous_average_amount": 4000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "11:45",
        "previous_location": "Thrissur",
        "current_location": "Thrissur",
        "transaction_frequency": 5,
        "account_age_days": 1200,
        "previous_risk_score": 60,
        "status": "Open",
    },
    {
        "customer_name": "Manoj Verma",
        "customer_id": "CUST-MV-019",
        "transaction_amount": 25000,
        "transaction_type": "Withdrawal",
        "location": "Varanasi",
        "previous_average_amount": 9000,
        "device_type": "Desktop",
        "is_new_device": True,
        "login_time": "14:00",
        "previous_location": "Varanasi",
        "current_location": "Varanasi",
        "transaction_frequency": 3,
        "account_age_days": 365,
        "previous_risk_score": 22,
        "status": "Under Review",
    },
    {
        "customer_name": "Geeta Chauhan",
        "customer_id": "CUST-GC-020",
        "transaction_amount": 20000,
        "transaction_type": "Payment",
        "location": "Agra",
        "previous_average_amount": 6500,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "16:00",
        "previous_location": "Mathura",
        "current_location": "Agra",
        "transaction_frequency": 6,
        "account_age_days": 700,
        "previous_risk_score": 58,
        "status": "Approved",
    },
    {
        "customer_name": "Harish Kumar",
        "customer_id": "CUST-HK-021",
        "transaction_amount": 17000,
        "transaction_type": "Transfer",
        "location": "Coimbatore",
        "previous_average_amount": 5500,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "08:30",
        "previous_location": "Coimbatore",
        "current_location": "Coimbatore",
        "transaction_frequency": 4,
        "account_age_days": 500,
        "previous_risk_score": 40,
        "status": "Open",
    },
    {
        "customer_name": "Ananya Das",
        "customer_id": "CUST-AD-022",
        "transaction_amount": 30000,
        "transaction_type": "Purchase",
        "location": "Kolkata",
        "previous_average_amount": 11000,
        "device_type": "Desktop",
        "is_new_device": False,
        "login_time": "17:30",
        "previous_location": "Howrah",
        "current_location": "Kolkata",
        "transaction_frequency": 7,
        "account_age_days": 200,
        "previous_risk_score": 45,
        "status": "Resolved",
    },
    # ============ LOW Cases ============
    {
        "customer_name": "Sunita Yadav",
        "customer_id": "CUST-SY-023",
        "transaction_amount": 5000,
        "transaction_type": "Payment",
        "location": "Jaipur",
        "previous_average_amount": 4500,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "10:00",
        "previous_location": "Jaipur",
        "current_location": "Jaipur",
        "transaction_frequency": 2,
        "account_age_days": 1500,
        "previous_risk_score": 10,
        "status": "Approved",
    },
    {
        "customer_name": "Ramesh Patel",
        "customer_id": "CUST-RP-024",
        "transaction_amount": 3000,
        "transaction_type": "Purchase",
        "location": "Surat",
        "previous_average_amount": 3500,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "12:00",
        "previous_location": "Surat",
        "current_location": "Surat",
        "transaction_frequency": 1,
        "account_age_days": 2000,
        "previous_risk_score": 5,
        "status": "Approved",
    },
    {
        "customer_name": "Usha Nambiar",
        "customer_id": "CUST-UN-025",
        "transaction_amount": 7500,
        "transaction_type": "Payment",
        "location": "Trivandrum",
        "previous_average_amount": 8000,
        "device_type": "Desktop",
        "is_new_device": False,
        "login_time": "11:30",
        "previous_location": "Trivandrum",
        "current_location": "Trivandrum",
        "transaction_frequency": 3,
        "account_age_days": 1800,
        "previous_risk_score": 8,
        "status": "Approved",
    },
    {
        "customer_name": "Dinesh Choudhary",
        "customer_id": "CUST-DC-026",
        "transaction_amount": 2500,
        "transaction_type": "Refund",
        "location": "Jodhpur",
        "previous_average_amount": 3000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "14:45",
        "previous_location": "Jodhpur",
        "current_location": "Jodhpur",
        "transaction_frequency": 1,
        "account_age_days": 1000,
        "previous_risk_score": 12,
        "status": "Resolved",
    },
    {
        "customer_name": "Fatima Begum",
        "customer_id": "CUST-FB-027",
        "transaction_amount": 6000,
        "transaction_type": "Payment",
        "location": "Hyderabad",
        "previous_average_amount": 5500,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "15:30",
        "previous_location": "Hyderabad",
        "current_location": "Hyderabad",
        "transaction_frequency": 2,
        "account_age_days": 900,
        "previous_risk_score": 15,
        "status": "Approved",
    },
    {
        "customer_name": "Ranjit Singh",
        "customer_id": "CUST-RS2-028",
        "transaction_amount": 4200,
        "transaction_type": "Transfer",
        "location": "Ludhiana",
        "previous_average_amount": 4000,
        "device_type": "Desktop",
        "is_new_device": False,
        "login_time": "09:30",
        "previous_location": "Ludhiana",
        "current_location": "Ludhiana",
        "transaction_frequency": 2,
        "account_age_days": 1100,
        "previous_risk_score": 7,
        "status": "Approved",
    },
    {
        "customer_name": "Chitra Venkatesh",
        "customer_id": "CUST-CV-029",
        "transaction_amount": 8500,
        "transaction_type": "Payment",
        "location": "Bangalore",
        "previous_average_amount": 9000,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "10:15",
        "previous_location": "Bangalore",
        "current_location": "Bangalore",
        "transaction_frequency": 3,
        "account_age_days": 730,
        "previous_risk_score": 18,
        "status": "Approved",
    },
    {
        "customer_name": "Sanjay Mishra",
        "customer_id": "CUST-SM-030",
        "transaction_amount": 4800,
        "transaction_type": "Withdrawal",
        "location": "Allahabad",
        "previous_average_amount": 5200,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "13:00",
        "previous_location": "Allahabad",
        "current_location": "Allahabad",
        "transaction_frequency": 2,
        "account_age_days": 1300,
        "previous_risk_score": 10,
        "status": "Approved",
    },
    {
        "customer_name": "Bhavana Reddy",
        "customer_id": "CUST-BR-031",
        "transaction_amount": 7000,
        "transaction_type": "Payment",
        "location": "Warangal",
        "previous_average_amount": 6800,
        "device_type": "Mobile",
        "is_new_device": False,
        "login_time": "11:00",
        "previous_location": "Warangal",
        "current_location": "Warangal",
        "transaction_frequency": 2,
        "account_age_days": 600,
        "previous_risk_score": 5,
        "status": "Approved",
    },
]


def _make_case_id(index: int) -> str:
    base_date = datetime(2026, 8, 1) + timedelta(days=index)
    return f"CASE-{base_date.strftime('%Y%m%d')}-{str(index + 1).zfill(4)}"


def seed_if_empty(db: Session):
    """Seed the database if no assessments exist."""
    existing = db.query(RiskAssessment).count()
    if existing > 0:
        return

    print("Seeding database with demo data...")

    for i, case_data in enumerate(SEED_CASES):
        # Create/get customer
        customer = db.query(Customer).filter(Customer.customer_id == case_data["customer_id"]).first()
        if not customer:
            customer = Customer(
                customer_id=case_data["customer_id"],
                name=case_data["customer_name"],
                account_age_days=case_data["account_age_days"],
                created_at=datetime.utcnow() - timedelta(days=case_data["account_age_days"]),
            )
            db.add(customer)
            db.flush()

        case_id = _make_case_id(i)
        created_at = datetime.utcnow() - timedelta(days=len(SEED_CASES) - i, hours=random.randint(0, 23))

        assessment = RiskAssessment(
            case_id=case_id,
            customer_id=case_data["customer_id"],
            customer_name=case_data["customer_name"],
            transaction_amount=case_data["transaction_amount"],
            transaction_type=case_data["transaction_type"],
            location=case_data["location"],
            previous_average_amount=case_data["previous_average_amount"],
            device_type=case_data["device_type"],
            is_new_device=case_data["is_new_device"],
            login_time=case_data["login_time"],
            previous_location=case_data["previous_location"],
            current_location=case_data["current_location"],
            transaction_frequency=case_data["transaction_frequency"],
            account_age_days=case_data["account_age_days"],
            previous_risk_score=case_data["previous_risk_score"],
            status=case_data["status"],
            created_at=created_at,
        )
        db.add(assessment)
        db.flush()

        # Run risk engine
        engine_data = {
            "transaction_amount": case_data["transaction_amount"],
            "previous_average_amount": case_data["previous_average_amount"],
            "is_new_device": case_data["is_new_device"],
            "previous_location": case_data["previous_location"],
            "current_location": case_data["current_location"],
            "login_time": case_data["login_time"],
            "transaction_frequency": case_data["transaction_frequency"],
            "account_age_days": case_data["account_age_days"],
            "previous_risk_score": case_data["previous_risk_score"],
            "device_type": case_data["device_type"],
        }
        result = _risk_engine.calculate_score(engine_data)
        explanation = _explanation_engine.generate(result["risk_level"], result["total_score"], result["factors"])
        recommendation = _recommendation_engine.get_recommendation(result["risk_level"], result["factors"])
        anomaly = _anomaly_engine.analyze(case_data["transaction_amount"], case_data["previous_average_amount"])

        for f in result["factors"]:
            factor = RiskFactor(
                assessment_id=assessment.id,
                factor_name=f["factor_name"],
                impact=f["impact"],
                score_contribution=f["score_contribution"],
                explanation=f["explanation"],
            )
            db.add(factor)

        full_explanation = {**explanation, "recommendation": recommendation, "anomaly": anomaly}
        assessment.risk_score = result["total_score"]
        assessment.risk_level = result["risk_level"]
        assessment.explanation = json.dumps(full_explanation)
        assessment.recommendation = recommendation["description"]
        assessment.analyzed_at = created_at + timedelta(seconds=random.randint(30, 120))

        # Audit log for each case
        db.add(AuditLog(
            timestamp=created_at,
            user="System",
            action="Assessment Created",
            case_id=case_id,
            description=f"Demo assessment created for {case_data['customer_name']}",
        ))
        db.add(AuditLog(
            timestamp=assessment.analyzed_at,
            user="System",
            action="Risk Analysis Executed",
            case_id=case_id,
            description=f"Risk score: {result['total_score']:.0f}/100, Level: {result['risk_level']}",
        ))

    db.commit()
    print(f"Seeded {len(SEED_CASES)} demo assessments.")
